name: CI

on:
  push:
    branches: [ "main" ]

  # trigger manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.WEB_HOST }}
          SSH_USER: ${{ secrets.WEB_HOST_USER }}
          SSH_KEY: ${{ secrets.WEB_HOST_KEY }}
      
      - name: Trigger deployment
        # run: ssh ${{ steps.ssh.outputs.SERVER }} ls      
        run: |
          ssh ${{ steps.ssh.outputs.SERVER }} <<'ENDSSH'
          cd projects/leanovate-web/
          echo "git pull"
          git pull https://github.com/gitmathub/leanovate-web.git
          npm install --no-audit
          npm run deploy:remote
          ENDSSH
