# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # trigger manually
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.WEB_HOST }}
          SSH_USER: ${{ secrets.WEB_HOST_USER }}
          SSH_KEY: ${{ secrets.WEB_HOST_KEY }}
      
      - name: ls
        # run: ssh ${{ steps.ssh.outputs.SERVER }} ls      
        run: ssh ${{ steps.ssh.outputs.SERVER }} <<'ENDSSH'
cd projects/leanovate-web/
echo "git pull"
git pull https://github.com/gitmathub/leanovate-web.git
npm install
npm run deploy:remote
ENDSSH
